### ISSUE TITLE
Next song is not played in playlist

### ISSUE THREAD

**Issue by nishantc7** [SubhrajitPrusty/ycl#18]
**Next song is not played in playlist and same song is played again**
When a playlist is added by playlist link we need to manually start next song and the same song is played unless done using the button `s : Start next song in playlist`.

**To Reproduce**
1. run `ycl -pl <playlist-link>`
2. wait for one song in queue to finish.
3. After the above step the same song is played again.

**Expected behavior**
The next song in queue to be played instead the same song is played

**Desktop**
 - OS: Arch Linux (Manjaro XFCE)
 - Version : latest commit

**Comment by SubhrajitPrusty** [comment]
Try the dev branch

**Comment by nishantc7** [comment]
working on dev
